spring:
  config:
    import: optional:file:.env[.properties]  
  application:
    name: activity-service
  mongodb:
    uri: ${MONGODB_URL}


server:
  port: 8082

eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

rabbitmq:
  exchange: 
    name: fitme.exchange
  queue:
    name: activity.queue
  routing:
    key: activity.tracking