spring:
  config:
    import: optional:file:.env[.properties]  
  application:
    name: activityservice
  mongodb:
    uri: ${MONGODB_URL}


server:
  port: 8082

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka